[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build --filter=@tradepath/api..."]

[start]
cmd = "cd apps/api && pnpm run start"
